[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "malkus"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "numba",
    "pandas",
    "pyarrow",
    "xarray",
    "zarr>=2.18,<3",
    "rasterio",
    "rioxarray",
    "matplotlib",
]
